export enum LightTheme {
  Primary = "#0078D4",
  DarkPrimary = "#106EBE",
  LightColor = "#F4F4F4",
  DarkColor = "#EAEAEA",
  Gray = "#C4C4C4",
  Error = "#A80000",
  ErrorText = "red",
  Success = "#107C10",
  TextNormal = "#323130",
  TextPrimary = "#CCCCCC",
  TextDisabled = "#A6A6A6",
  BackgroundBlackWhite = "#FFFFFF",
  Background = "#FFFFFF",
  Background2 = "#F8F8F8",
  Background3 = "#F8F8F8",
  Background4 = "#FFFFFF",
  BorderColor = "#EAEAEA",
  BorderColor2 = "#C4C4C4",
}
export enum DarkTheme {
  Primary = "#69AFE5",
  DarkPrimary = "#B3D6FC",
  LightColor = "#252423",
  DarkColor = "#212121",
  Gray = "#696969",
  Error = "#F1707B",
  ErrorText = "red",
  Success = "#6BB700",
  TextNormal = "#FFFFFF",
  TextPrimary = "#333333",
  TextDisabled = "#A19F9D",
  BackgroundBlackWhite = "#000000",
  Background = "#333333",
  Background2 = "#333333",
  Background3 = "#212121",
  Background4 = "#212121",
  BorderColor = "#000000",
  BorderColor2 = "#C4C4C4",
}
export enum ThemeColor {
  Primary = "Primary",
  DarkPrimary = "DarkPrimary",
  LightColor = "LightColor",
  DarkColor = "DarkColor",
  Gray = "Gray",
  Error = "Error",
  ErrorText = "ErrorText",
  Success = "Success",
  TextNormal = "TextNormal",
  TextPrimary = "TextPrimary",
  TextDisabled = "TextDisabled",
  Background = "Background",
  BackgroundBlackWhite = "BackgroundBlackWhite",
  Background2 = "Background2",
  Background3 = "Background3",
  Background4 = "Background4",
  BorderColor = "BorderColor",
  BorderColor2 = "BorderColor2",
}
