export enum ActCalendarTypeKeys {
  UPDATE_WORKING_APPOINTMENT = "UPDATE_WORKING_APPOINTMENT",
  UPDATE_WORKING_CALENDAR = "UPDATE_WORKING_CALENDAR",
  UPDATE_SELECTED_APPOINTMENTS = "UPDATE_SELECTED_APPOINTMENTS",
  RESET_CALENDAR_STORE = "RESET_CALENDAR_STORE",
}
