export enum ActionNotificationTypeKeys {
  GET_NOTIFICATONS = "GET_NOTIFICATONS",
  REMOVE_NOTIFICATION_ITEM = "REMOVE_NOTIFICATION_ITEM",
  REMOVE_ALL_NOTIFICATION_ITEM = "REMOVE_ALL_NOTIFICATION_ITEM",
  CHANGE_NOTIFICATION_LOADING_STATUS = "CHANGE_NOTIFICATION_LOADING_STATUS",
  UPDATE_NOTIFICATION_LIST = "UPDATE_NOTIFICATION_LIST",
  ADD_A_NOTIFICATION_ITEM = "ADD_A_NOTIFICATION_ITEM",
  LOADING_WORKFLOW = "LOADING_WORKFLOW",
  SIGNALR_GETDATA = "SIGNALR_GETDATA",
  UPDATE_TOAST_CONTAINER = "UPDATE_TOAST_CONTAINER"
}
