export enum ActSensorTypeKeys {
  UPDATE_SENSOR_WORKING_TAB = "UPDATE_SENSOR_WORKING_TAB",
  UPDATE_SENSOR_WORKING_LIST = "UPDATE_SENSOR_WORKING_LIST",
  UPDATE_SENSOR_TYPE_OPTIONS = "UPDATE_SENSOR_TYPE_OPTIONS",
  UPDATE_EDIT_SENSOR = "UPDATE_EDIT_SENSOR",
  UPDATE_EDIT_CONTROLLER = "UPDATE_EDIT_CONTROLLER",
  UPDATE_EDIT_CONFIGURATION = "UPDATE_EDIT_CONFIGURATION",
  UPDATE_WORKING_ORGANIZATION = "UPDATE_WORKING_ORGANIZATION",
  RESET_SENSOR_REDUX_STORE = "RESET_SENSOR_REDUX_STORE",
}
