export enum ActUserTypeKeys {
  GET_ORGANIZATION_INFORMATION = "GET_ORGANIZATION_INFORMATION",
  UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION",
  START_GET_USER = "START_GET_USER",
  END_GET_USER = "END_GET_USER",
  CHANGE_BREADCRUMB_DATA = "CHANGE_BREADCRUMB_DATA",
  CHANGE_BREADCRUMB_DATA2 = "CHANGE_BREADCRUMB_DATA2",
  LOADING_BREADCRUMB_DATA = "LOADING_BREADCRUMB_DATA",
}
